FROM php:8.2-cli

RUN apt-get update && apt-get install -y \
    git unzip libsqlite3-dev libzip-dev libicu-dev \
    && docker-php-ext-configure intl \
    && docker-php-ext-install pdo_sqlite zip intl

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /app
